export const products = [

{
  id: 1,
  name: "Royal Oud",
  brand: "Amber Sky",
  gender: "men",
  tags: ["luxury","gift","rich","premium"],
  mood: ["royal","mature","confident"],
  season: ["winter","evening"],
  useCase: ["gift","formal","events"],
  notes: ["oud","wood","spice"],
  ageGroup: ["middle","old"],
  relationship: ["husband","father"],
  occasion: ["office","function","evening"],
  intensity: "heavy",
  sweetness: "no",
  price: 2499,
  buyersThisMonth: 650,
  bestSeller: true,
  priorityWeight: 1.2,
  image: "https://res.cloudinary.com/dfwtbkrrd/image/upload/v1770591806/Royal-oud_pucxpz.jpg"
},

{
  id: 2,
  name: "Night Ember",
  brand: "Amber Sky",
  gender: "men",
  tags: ["bold","luxury","night","date"],
  mood: ["mysterious","confident"],
  season: ["winter","night"],
  useCase: ["date","party","romantic"],
  notes: ["leather","smoke","amber"],
  ageGroup: ["young","middle"],
  relationship: ["boyfriend","husband"],
  occasion: ["club","party","date"],
  intensity: "heavy",
  sweetness: "no",
  price: 2699,
  buyersThisMonth: 820,
  bestSeller: true,
  priorityWeight: 1.3,
  image: "https://res.cloudinary.com/dfwtbkrrd/image/upload/v1770591808/pexels-arturoaez225-10701986_qo0v5m.jpg"
},

{
  id: 3,
  name: "Ocean Force",
  brand: "Amber Sky",
  gender: "men",
  tags: ["fresh","daily","clean","safe"],
  mood: ["energetic","cool"],
  season: ["summer","day"],
  useCase: ["office","daily","college"],
  notes: ["marine","citrus","fresh"],
  ageGroup: ["young"],
  relationship: ["boyfriend","brother","son"],
  occasion: ["office","travel","daily"],
  intensity: "light",
  sweetness: "no",
  price: 1999,
  buyersThisMonth: 520,
  bestSeller: false,
  priorityWeight: 1.0,
  image: "https://res.cloudinary.com/dfwtbkrrd/image/upload/v1770591805/pexels-valeriya-1961789_vwltxm.jpg"
},

{
  id: 4,
  name: "Spice Vault",
  brand: "Amber Sky",
  gender: "men",
  tags: ["warm","professional","spicy"],
  mood: ["serious","confident"],
  season: ["winter","office"],
  useCase: ["office","meetings"],
  notes: ["cardamom","pepper","wood"],
  ageGroup: ["middle"],
  relationship: ["husband","father"],
  occasion: ["office","formal"],
  intensity: "medium",
  sweetness: "no",
  price: 2299,
  buyersThisMonth: 450,
  bestSeller: false,
  priorityWeight: 1.0,
  image: "https://res.cloudinary.com/dfwtbkrrd/image/upload/v1770591803/pexels-valeriya-1961794_gyppne.jpg"
},

{
  id: 5,
  name: "Dark Whiskey",
  brand: "Amber Sky",
  gender: "men",
  tags: ["luxury","gift","evening"],
  mood: ["warm","sensual"],
  season: ["winter","evening"],
  useCase: ["date","anniversary"],
  notes: ["whiskey","oak","vanilla"],
  ageGroup: ["middle"],
  relationship: ["husband"],
  occasion: ["party","anniversary"],
  intensity: "heavy",
  sweetness: "slight",
  price: 2799,
  buyersThisMonth: 610,
  bestSeller: true,
  priorityWeight: 1.2,
  image: "https://res.cloudinary.com/dfwtbkrrd/image/upload/v1770591798/pexels-cafepolverini-10838598_djhy9u.jpg"
},

/* ---------- WOMEN ---------- */

{
  id: 6,
  name: "Velvet Rose",
  brand: "Amber Sky",
  gender: "women",
  tags: ["romantic","gift","classic"],
  mood: ["lovely","feminine"],
  season: ["winter","evening"],
  useCase: ["date","anniversary"],
  notes: ["rose","vanilla","musk"],
  ageGroup: ["young","middle"],
  relationship: ["girlfriend","wife"],
  occasion: ["date","anniversary"],
  intensity: "medium",
  sweetness: "sweet",
  price: 2199,
  buyersThisMonth: 720,
  bestSeller: true,
  priorityWeight: 1.2,
  image: "https://res.cloudinary.com/dfwtbkrrd/image/upload/v1770591797/pexels-jay-soundo-2148060180-33820349_omzzm8.jpg"
},

{
  id: 7,
  name: "Vanilla Blossom",
  brand: "Amber Sky",
  gender: "women",
  tags: ["cute","sweet","young"],
  mood: ["playful","soft"],
  season: ["spring","day"],
  useCase: ["college","casual"],
  notes: ["vanilla","floral"],
  ageGroup: ["young"],
  relationship: ["girlfriend","sister"],
  occasion: ["party","date"],
  intensity: "light",
  sweetness: "sweet",
  price: 1999,
  buyersThisMonth: 680,
  bestSeller: true,
  priorityWeight: 1.1,
  image: "https://res.cloudinary.com/dfwtbkrrd/image/upload/v1770591798/pexels-yusuf-arslan-2018836-3640668_mlny2y.jpg"
},

{
  id: 8,
  name: "White Jasmine",
  brand: "Amber Sky",
  gender: "women",
  tags: ["elegant","classic","soft"],
  mood: ["calm","graceful"],
  season: ["summer","day"],
  useCase: ["function","daily"],
  notes: ["jasmine","white flowers"],
  ageGroup: ["middle"],
  relationship: ["wife","mother"],
  occasion: ["function","evening"],
  intensity: "light",
  sweetness: "mild",
  price: 1899,
  buyersThisMonth: 390,
  bestSeller: false,
  priorityWeight: 1.0,
  image: "https://res.cloudinary.com/dfwtbkrrd/image/upload/v1770591796/pexels-felipepelaquim-1895015_a6za8p.jpg"
},

{
  id: 9,
  name: "Berry Kiss",
  brand: "Amber Sky",
  gender: "women",
  tags: ["fun","young","gift"],
  mood: ["playful","happy"],
  season: ["spring","day"],
  useCase: ["date","casual"],
  notes: ["berry","raspberry"],
  ageGroup: ["young"],
  relationship: ["girlfriend","sister"],
  occasion: ["date","party"],
  intensity: "light",
  sweetness: "sweet",
  price: 1799,
  buyersThisMonth: 550,
  bestSeller: false,
  priorityWeight: 1.0,
  image: "https://res.cloudinary.com/dfwtbkrrd/image/upload/v1770591797/pexels-george-sistonen-952755-7247803_w6li0m.jpg"
},

{
  id: 10,
  name: "Golden Gardenia",
  brand: "Amber Sky",
  gender: "women",
  tags: ["luxury","gift","premium"],
  mood: ["elegant","romantic"],
  season: ["winter","evening"],
  useCase: ["anniversary","gift"],
  notes: ["gardenia","honey"],
  ageGroup: ["middle"],
  relationship: ["wife"],
  occasion: ["anniversary","evening"],
  intensity: "medium",
  sweetness: "sweet",
  price: 2399,
  buyersThisMonth: 610,
  bestSeller: true,
  priorityWeight: 1.2,
  image: "https://res.cloudinary.com/dfwtbkrrd/image/upload/v1770591791/pexels-valeriya-1961793_fiedhw.jpg"
},

/* ---------- UNISEX ---------- */

{
  id: 11,
  name: "Citrus Rush",
  brand: "Amber Sky",
  gender: "unisex",
  tags: ["fresh","safe","daily"],
  mood: ["energetic","clean"],
  season: ["summer","day"],
  useCase: ["office","daily"],
  notes: ["lemon","bergamot","orange"],
  ageGroup: ["young"],
  relationship: ["friend","colleague","couple"],
  occasion: ["travel","daily"],
  intensity: "light",
  sweetness: "no",
  price: 1999,
  buyersThisMonth: 430,
  bestSeller: false,
  priorityWeight: 1.0,
  image: "https://res.cloudinary.com/dfwtbkrrd/image/upload/v1770591791/pexels-khulood-abdulghani-195928257-12456282_hlfyti.jpg"
},

{
  id: 12,
  name: "Fresh Mint",
  brand: "Amber Sky",
  gender: "unisex",
  tags: ["clean","fresh","office"],
  mood: ["calm","refreshing"],
  season: ["summer","day"],
  useCase: ["office","daily"],
  notes: ["mint","green"],
  ageGroup: ["young"],
  relationship: ["friend","colleague"],
  occasion: ["office","daily"],
  intensity: "light",
  sweetness: "no",
  price: 1699,
  buyersThisMonth: 470,
  bestSeller: false,
  priorityWeight: 1.0,
  image: "https://res.cloudinary.com/dfwtbkrrd/image/upload/v1770591788/pexels-dina-nasyrova-2006209-3788293_oetu5h.jpg"
},

{
  id: 13,
  name: "Soft Musk",
  brand: "Amber Sky",
  gender: "unisex",
  tags: ["romantic","soft","intimate"],
  mood: ["calm","sensual"],
  season: ["winter","evening"],
  useCase: ["date","couple"],
  notes: ["musk","powdery"],
  ageGroup: ["middle"],
  relationship: ["couple","partner"],
  occasion: ["evening","date"],
  intensity: "light",
  sweetness: "mild",
  price: 1899,
  buyersThisMonth: 520,
  bestSeller: false,
  priorityWeight: 1.0,
  image: "https://res.cloudinary.com/dfwtbkrrd/image/upload/v1770591787/pexels-khabbab-abdelmaqsoud-5536074-11295329_p3w1ee.jpg"
},

{
  id: 14,
  name: "Wedding Bloom",
  brand: "Amber Sky",
  gender: "women",
  tags: ["wedding","luxury","gift"],
  mood: ["romantic","special"],
  season: ["spring","wedding"],
  useCase: ["wedding","bridal"],
  notes: ["rose","peony","vanilla"],
  ageGroup: ["young"],
  relationship: ["bride","wife"],
  occasion: ["wedding"],
  intensity: "medium",
  sweetness: "sweet",
  price: 2599,
  buyersThisMonth: 780,
  bestSeller: true,
  priorityWeight: 1.3,
  image: "https://res.cloudinary.com/dfwtbkrrd/image/upload/v1770591784/pexels-daria-liudnaya-8166566_twjlin.jpg"
},

{
  id: 15,
  name: "Anniversary Oud",
  brand: "Amber Sky",
  gender: "men",
  tags: ["luxury","gift","anniversary"],
  mood: ["warm","romantic"],
  season: ["winter","evening"],
  useCase: ["anniversary","date"],
  notes: ["oud","amber"],
  ageGroup: ["middle"],
  relationship: ["husband"],
  occasion: ["anniversary","evening"],
  intensity: "heavy",
  sweetness: "no",
  price: 2899,
  buyersThisMonth: 590,
  bestSeller: false,
  priorityWeight: 1.1,
  image: "https://res.cloudinary.com/dfwtbkrrd/image/upload/v1770591786/pexels-keifercosta-11216317_ak2ft2.jpg"
},

{
  id: 16,
  name: "Morning Breeze",
  brand: "Amber Sky",
  gender: "unisex",
  tags: ["fresh","daily","clean"],
  mood: ["calm","light"],
  season: ["summer","day"],
  useCase: ["daily","office"],
  notes: ["fresh","green tea"],
  ageGroup: ["young"],
  relationship: ["friend","colleague"],
  occasion: ["daily","office"],
  intensity: "light",
  sweetness: "no",
  price: 1599,
  buyersThisMonth: 410,
  bestSeller: false,
  priorityWeight: 1.0,
  image: "https://res.cloudinary.com/dfwtbkrrd/image/upload/v1770591784/pexels-hamza01nsr-12562775_brsulj.jpg"
},

{
  id: 17,
  name: "Office Clean",
  brand: "Amber Sky",
  gender: "men",
  tags: ["office","safe","professional"],
  mood: ["clean","serious"],
  season: ["all"],
  useCase: ["office","daily"],
  notes: ["lavender","citrus"],
  ageGroup: ["young","middle"],
  relationship: ["husband","boyfriend","colleague"],
  occasion: ["office","daily"],
  intensity: "light",
  sweetness: "no",
  price: 1799,
  buyersThisMonth: 460,
  bestSeller: false,
  priorityWeight: 1.0,
  image: "https://res.cloudinary.com/dfwtbkrrd/image/upload/v1770591784/pexels-jay-soundo-2148060180-33820368_ct5ah6.jpg"
},

{
  id: 18,
  name: "Sweet Cloud",
  brand: "Amber Sky",
  gender: "women",
  tags: ["sweet","cute","gift"],
  mood: ["cozy","soft"],
  season: ["winter","evening"],
  useCase: ["date","gift"],
  notes: ["marshmallow","vanilla"],
  ageGroup: ["young"],
  relationship: ["girlfriend","sister"],
  occasion: ["date","party"],
  intensity: "medium",
  sweetness: "sweet",
  price: 2099,
  buyersThisMonth: 640,
  bestSeller: true,
  priorityWeight: 1.1,
  image: "https://res.cloudinary.com/dfwtbkrrd/image/upload/v1770591781/pexels-mearlywan-307951439-14311564_vsbs8z.jpg"
},

{
  id: 19,
  name: "Amber Soul",
  brand: "Amber Sky",
  gender: "unisex",
  tags: ["warm","romantic","gift"],
  mood: ["calm","intimate"],
  season: ["winter","evening"],
  useCase: ["date","couple"],
  notes: ["amber","wood"],
  ageGroup: ["middle"],
  relationship: ["couple","partner"],
  occasion: ["evening","date"],
  intensity: "medium",
  sweetness: "mild",
  price: 2199,
  buyersThisMonth: 510,
  bestSeller: false,
  priorityWeight: 1.0,
  image: "https://res.cloudinary.com/dfwtbkrrd/image/upload/v1770591780/pexels-khulood-abdulghani-195928257-12456260_fms4wj.jpg"
},

{
  id: 20,
  name: "Leather Night",
  brand: "Amber Sky",
  gender: "men",
  tags: ["bold","night","luxury"],
  mood: ["dominant","confident"],
  season: ["winter","night"],
  useCase: ["party","date"],
  notes: ["leather","smoke"],
  ageGroup: ["young"],
  relationship: ["boyfriend","husband"],
  occasion: ["club","party"],
  intensity: "heavy",
  sweetness: "no",
  price: 2799,
  buyersThisMonth: 720,
  bestSeller: true,
  priorityWeight: 1.2,
  image: "https://res.cloudinary.com/dfwtbkrrd/image/upload/v1770591781/pexels-linda-kokina-1657496-5812092_jizjxz.jpg"
}

];
